/* automatically generated by rust-bindgen 0.71.1 */

use super::*;
use libc::FILE;

unsafe extern "C" {
    pub fn MIR_gen_init(ctx: MIR_context_t);
}
unsafe extern "C" {
    pub fn MIR_gen_set_debug_file(ctx: MIR_context_t, f: *mut FILE);
}
unsafe extern "C" {
    pub fn MIR_gen_set_debug_level(ctx: MIR_context_t, debug_level: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn MIR_gen_set_optimize_level(ctx: MIR_context_t, level: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn MIR_gen(ctx: MIR_context_t, func_item: MIR_item_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn MIR_set_gen_interface(ctx: MIR_context_t, func_item: MIR_item_t);
}
unsafe extern "C" {
    pub fn MIR_set_lazy_gen_interface(ctx: MIR_context_t, func_item: MIR_item_t);
}
unsafe extern "C" {
    pub fn MIR_set_lazy_bb_gen_interface(ctx: MIR_context_t, func_item: MIR_item_t);
}
unsafe extern "C" {
    pub fn MIR_gen_finish(ctx: MIR_context_t);
}
