[package]
name = "mir-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "mir"

[dependencies]
libc = "0.2.121"
mir-sys = { path = "./mir-sys" }

[workspace]

[dev-dependencies]
expect-test = "1.2.2"
